### ISSUE TITLE
Feature: User can click on a button to generate a random joke

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/got-jokes#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on button the generate a random joke

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the big "click here" button and generate a random joke.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/127217173-4edc0c26-8f25-4c45-aa8f-049024fbf09d.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML foundation and style using CSS. Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Add a `div[data-view="generate-joke"]` to the HTML.
- [x] Add a `div[data-view="jokes"]` to the HTML.
- [x] Using AJAX, retrieve the setup of the joke, and store the setup into a data model.
- [x] Listen for click events on the "click here" button that will generate a joke and display the jokes window/view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
