### ISSUE TITLE
Feature: User can click on button to see the punchline of a joke

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/got-jokes#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a button to see the punchline of a joke.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user has generated a random joke, they are able to see and click on a new button to get the punchline of the joke.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/127241660-0bd239f1-00e0-44b3-9b5e-7b77c670a652.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the Punchline! button with HTML and CSS.
- [x] Hide the button.
- [x] Query the button.
- [x] Add functionality to the previous joke generator function so that it shows the Punchline button after a joke is generated.
- [x] Using AJAX, retrieve the punchline of the joke and store it into the data model.
- [x] Append the punchline of the joke into a new text bubble under the setup of the joke.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
