### ISSUE TITLE
Feature: User can click on a button to generate a new joke

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/got-jokes#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on the "More Jokes!" button to generate a new joke.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the punchline is revealed for the first, initial joke, you can click on a button to generate a new joke.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/127575573-8ae31aac-f0b4-4f42-ada6-405feeeb59ba.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add in a new "More Jokes!" button into the HTML and edit it with CSS.
- [x] Hide the More Jokes button.
- [x] Add functionality to the punchline button so that when it's clicked, the punchline button itself disappears and the More Jokes button appears.
- [x] Listen for a click event on the More Jokes button so that it looks like the user is texting with someone.
- [x] The More Jokes button will append the new joke to the left. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
