### ISSUE TITLE
Feature: User can click on a button (laugh emoji or snooze emoji) to “react” to a joke

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/got-jokes#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a button (laugh emoji, snooze emoji, or next) to “react” to a new joke. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a emoji button to react to a joke and the emoji will appear on the right as a blue text bubble as if it's a real time texting conversation

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/127583438-adb06b25-d5a5-4adc-a5d8-bfbf5b446954.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add in the buttons for the emojis and style them with CSS.
- [x] Position the buttons correctly on the bottom.
- [x] Query the emojis.
- [x] Listen for click events on the emojis so that they show up as a reaction for the user.
- [x] If user reacts with a laughing emoji, save it into the data model.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
