### ISSUE TITLE
Feature: User can see their collection of funny jokes and go back to generating new jokes

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/got-jokes#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their collection of funny jokes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see their collection of all the jokes that they reacted to with a funny emoji

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/128414460-e1a7fa9d-bdc7-4184-9f72-d6bdb6f4a007.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Code in the collection button into the HTML.
- [x] Hide the button so that it only appears after a reaction.
- [x] By clicking on the collection button, a user should be able to see all of the jokes that they reacted to with a laughing emoji.
- [x] Create the back to jokes button and shows up after the collection button is pressed.
- [x] In the collection screen, add the laughing emoji at the top. 
- [x] From the collection screen a user can go back to seeing more jokes with a emptied out joke container.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
